# -*- coding: utf-8 -*-
"""HOPE method 1.2.0: Puzzle 7 phase 1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13kXsZjapJ4YQBEo6Ss2Y1HxBMEWREosY

#
'''
HOPE Method 1.2.0 Puzzle 7 Phase 1

Author: Michellie Hernandez
AI-assisted development:
ChatGPT and Gemini were used for curriculum drafting, coding assistance and editorial feedback.


🧬 Puzzle 7 — Validate a BCR Coding Sequence
Biological problem
You receive a nucleotide sequence from a BCR sequencing dataset. Before translating it into an amino-acid sequence, you want to check whether it has a plausible coding structure.
For this simplified exercise, assume a complete BCR coding sequence should:
Begin with AUG in mRNA (or ATG if represented as DNA).
Have a length divisible by 3.
Contain a stop codon at the end.
Have no internal stop codons before the final codon.
This is a simplified benchmark rule. Real BCR datasets can contain partial V(D)J sequences, different sequence representations, and annotations that require more nuanced handling.
Your test sequence
Start with this DNA sequence:
bcr_dna = "ATGGCCATTGTATGGTAA"
Your goal is to determine whether it passes the four checks.


Step 1 — Check the start
Write a condition that asks:
Does the sequence start with ATG?
Hint:
sequence.startswith(...)

Step 2 — Check the coding frame
Determine whether the sequence length is divisible by 3.
For example:

len(bcr_dna) % 3
If the result is 0, the sequence has complete codons.

Step 3 — Find the stop codon
The three standard DNA stop codons are:
UAA
UAG
UGA

Step 4 — Check for internal stop codons
Now determine whether TAA, TAG, or TGA occurs before the final codon.
This is important because:


🎯 Your coding challenge
Create a function:
def validate_coding_sequence(sequence):
It should return:
"Valid coding sequence"
if all four conditions pass.
Otherwise, return an informative message such as:

"Invalid: missing start codon"
"Invalid: sequence length is not divisible by 3"
"Invalid: missing terminal stop codon"
"Invalid: internal stop codon detected"
Test it on these four sequences

bcr1 = "ATGGCCATTGTATGGTAA"

bcr2 = "GGCCATTGTATGGTAA"

bcr3 = "ATGGCCATTTGGTAA"

bcr4 = "ATGGCCATTTAA GGTAA".replace(" ", "")


'''
"""

def classify_sequence(sequence):
  aa_in_protein = {
    "Alanine": "A",
    "Arginine": "R",
    "Asparagine": "N",
    "Aspartic acid": "D",
    "Cysteine": "C",
    "Glutamic acid": "E",
    "Glutamine": "Q",
    "Glycine": "G",
    "Histidine": "H",
    "Isoleucine": "I",
    "Leucine": "L",
    "Lysine": "K",
    "Methionine": "M",
    "Phenylalanine": "F",
    "Proline": "P",
    "Serine": "S",
    "Threonine": "T",
    "Tryptophan": "W",
    "Tyrosine": "Y",
    "Valine": "V"
}
  if set(sequence).issubset({"A", "T", "G", "C"}):
        return "Sequence is DNA"

  elif set(sequence).issubset({"A", "U", "G", "C"}):
        return "Sequence is RNA"
  elif set(sequence).issubset(set(aa_in_protein.values())):
        return "Sequence is a Protein"
  else:
        return "Sequence is Unknown"



def transcribe_dna_to_rna(dna_sequence):
  return dna_sequence.replace("T", "U")

def find_codons(sequence):
  codons = []
  for i in range(0, len(sequence), 3):
    codon = sequence[i:i+3]
    if set(codon).issubset({"A", "U", "G", "C"}):
      codons.append(codon)
    else:
      return "Invalid sequence"
  return codons

def translate_rna_to_protein(rna_sequence):
  codons = find_codons(rna_sequence)
  aa_in_protein = {
        "Alanine": {"code":"A", "codon": ["GCU", "GCC", "GCA", "GCG"]},
        "Arginine": {"code" : "R", "codon": ["CGU", "CGC", "CGA", "CGG", "AGA", "AGG"]},
        "Asparagine": {"code": "N", "codon": ["AAU", "AAC"]},
        "Aspartic acid": {"code": "D", "codon": ["GAU", "GAC"]},
        "Cysteine": {"code": "C", "codon": ["UGU", "UGC"]},
        "Glutamic acid": {"code": "E", "codon": ["GAA", "GAG"]},
        "Glutamine": {"code": "Q", "codon": ["CAA", "CAG"]},
        "Glycine": {"code": "G", "codon": ["GGU", "GGC", "GGA", "GGG"]},
        "Histidine": {"code": "H", "codon": ["CAU", "CAC"]},
        "Isoleucine": {"code": "I", "codon": ["AUU", "AUC", "AUA"]},
        "Leucine": {"code": "L", "codon": ["UUA", "UUG", "CUU", "CUC", "CUA", "CUG"]},
        "Lysine": {"code": "K", "codon": ["AAA", "AAG"]},
        "Methionine": {"code": "M", "codon": "AUG"},
        "Phenylalanine": {"code" : "F", "codon": ["UUU", "UUC"]},
        "Proline": {"code" : "P", "codon": ["CCU", "CCC", "CCA", "CCG"]},
        "Serine": {"code" : "S", "codon": ["AGU", "AGC", "UCU", "UCC", "UCA", "UCG"]},
        "Threonine": {"code" : "T", "codon": ["ACU", "ACC", "ACA", "ACG"]},
        "Tryptophan": {"code" : "W", "codon": ["UGG"]},
        "Tyrosine": {"code" : "Y", "codon": ["UAU", "UAC"]},
        "Valine": {"code" : "V", "codon": ["GUU", "GUC", "GUA", "GUG"]},
        "Stop codons": {"code" : "STOP", "codon": ["UAA", "UAG", "UGA"]}
    }

  aa_sequence = []
  for codon in codons:
    found_match = False # Flag to check if a match was found
    for aa_name, info in aa_in_protein.items(): # Iterate through amino acid info
      # Ensure info["codon"] is always a list for consistent checking
      codons_list = info["codon"] if isinstance(info["codon"], list) else [info["codon"]]
      if codon in codons_list:
        aa_sequence.append(info["code"])
        found_match = True
        break # Found a match, move to the next RNA codon
    if not found_match:
      aa_sequence.append("X") # Placeholder for unrecognised codon
  return "".join(aa_sequence)


def central_dogma(dna_sequence):
  return translate_rna_to_protein(transcribe_dna_to_rna(dna_sequence))


def validate_coding_sequence(sequence):
  sequence_type = classify_sequence(sequence)

  if sequence_type == "Sequence is DNA":
    rna_sequence = sequence.replace("T", "U")
  elif sequence_type == "Sequence is RNA":
    rna_sequence = sequence
  else:
    return sequence, "Invalid sequence"

  invalid = ""
  check_point = 0
  codons = find_codons(rna_sequence)
  stop_codons = ["UAA", "UAG", "UGA"]
  
  if rna_sequence.startswith("AUG") == False:
    invalid += "Invalid: missing start codon"
  else:
    check_point +=1

  if not len(rna_sequence) % 3 == 0:
    invalid += " Invalid: sequence length is not divisible by 3"
  else:
    check_point +=1

  if codons[-1] not in stop_codons:
    invalid += " Invalid: missing terminal stop codon"
  else:
      check_point +=1

  if any(codon in stop_codons for codon in codons[:-1]):
      invalid += " Invalid: internal stop codon detected"
  else:
    check_point +=1

  if check_point == 4:
    return sequence, "Valid coding sequence. Passing all 4 checkpoints"
  else:
    return sequence, invalid


bcr1 = "ATGGCCATTGTATGGTAA"

bcr2 = "GGCCATTGTATGGTAA"

bcr3 = "ATGGCCATTTGGTAA"

bcr4 = "ATGGCCATTTAA GGTAA"

bcr5 = "ATGGCCATTUGAUGGTAA"

print("BCR1: ", validate_coding_sequence(bcr1))
print("BCR2: ", validate_coding_sequence(bcr2))
print("BCR3: ", validate_coding_sequence(bcr3))
print("BCR4: ", validate_coding_sequence(bcr4))
print("BCR5: ", validate_coding_sequence(bcr5))
