# -*- coding: utf-8 -*-
"""HOPE method 1.2.0 Puzzle 2-6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16CQcVWgahy1Kn_NwpP5yvybgs9v7RkGp

#
'''HOPE Method 1.2.0 Puzzles 2-6
Authors: ChatGPT, Gemini, Michellie Hernandez
Puzzle 2 - 6

Theme: From BCR nucleotide sequence → antibody protein sequence

Today we make the first biological connection at the center of the HOPE Method 1.2.0.

You will learn how a nucleotide sequence can be translated into an amino-acid sequence.

🧬 Biological problem

A BCR contains an immunoglobulin nucleotide sequence.

The nucleotide sequence is read in groups of three nucleotides called codons.

Each codon corresponds to an amino acid during translation.



Python skill

Today you’ll practice:

strings
indexing
slicing
range()
for loops
dictionaries
building a function
🧩 Your challenge

Puzzle 2:
Start with this nucleotide sequence:

bcr = "ATGGCCATTGTA"

Part 1 — Find the codons

Write Python code that extracts the sequence in groups of three:

Part 2 — Create a small genetic-code dictionary

Puzzle 3: Translate a codon into an amino acid

Puzzle 4: Translate an entire nucleotide sequence

Puzzle 5: Build a codon → amino-acid dictionary

Puzzle 6: Translate BCR sequences to RNA sequence to amino acid sequence programmatically.
'''
"""

def characters_in_sequence(sequence):
  return len(sequence)

def classify_sequence(sequence):
  aa_in_protein = {
    "Alanine": "A",
    "Arginine": "R",
    "Asparagine": "N",
    "Aspartic acid": "D",
    "Cysteine": "C",
    "Glutamic acid": "E",
    "Glutamine": "Q",
    "Glycine": "G",
    "Histidine": "H",
    "Isoleucine": "I",
    "Leucine": "L",
    "Lysine": "K",
    "Methionine": "M",
    "Phenylalanine": "F",
    "Proline": "P",
    "Serine": "S",
    "Threonine": "T",
    "Tryptophan": "W",
    "Tyrosine": "Y",
    "Valine": "V"
}
  if set(sequence).issubset({"A", "T", "G", "C"}):
        return "Sequence is DNA"

  elif set(sequence).issubset({"A", "U", "G", "C"}):
        return "Sequence is RNA"
  elif set(sequence).issubset(set(aa_in_protein.values())):
        return "Sequence is a Protein"
  else:
        return "Sequence is Unknown"

def transcribe_dna_to_rna(dna_sequence):
  return dna_sequence.replace("T", "U")

def find_codons(sequence):
  codons = []
  for i in range(0, len(sequence), 3):
    codon = sequence[i:i+3]
    codons.append(codon)
  return codons

def translate_rna_to_protein(rna_sequence):
  codons = find_codons(rna_sequence)
  aa_in_protein = {
        "Alanine": {"code":"A", "codon": ["GCU", "GCC", "GCA", "GCG"]},
        "Arginine": {"code" : "R", "codon": ["CGU", "CGC", "CGA", "CGG", "AGA", "AGG"]},
        "Asparagine": {"code": "N", "codon": ["AAU", "AAC"]},
        "Aspartic acid": {"code": "D", "codon": ["GAU", "GAC"]},
        "Cysteine": {"code": "C", "codon": ["UGU", "UGC"]},
        "Glutamic acid": {"code": "E", "codon": ["GAA", "GAG"]},
        "Glutamine": {"code": "Q", "codon": ["CAA", "CAG"]},
        "Glycine": {"code": "G", "codon": ["GGU", "GGC", "GGA", "GGG"]},
        "Histidine": {"code": "H", "codon": ["CAU", "CAC"]},
        "Isoleucine": {"code": "I", "codon": ["AUU", "AUC", "AUA"]},
        "Leucine": {"code": "L", "codon": ["UUA", "UUG", "CUU", "CUC", "CUA", "CUG"]},
        "Lysine": {"code": "K", "codon": ["AAA", "AAG"]},
        "Methionine": {"code": "M", "codon": "AUG"},
        "Phenylalanine": {"code" : "F", "codon": ["UUU", "UUC"]},
        "Proline": {"code" : "P", "codon": ["CCU", "CCC", "CCA", "CCG"]},
        "Serine": {"code" : "S", "codon": ["AGU", "AGC", "UCU", "UCC", "UCA", "UCG"]},
        "Threonine": {"code" : "T", "codon": ["ACU", "ACC", "ACA", "ACG"]},
        "Tryptophan": {"code" : "W", "codon": ["UGG"]},
        "Tyrosine": {"code" : "Y", "codon": ["UAU", "UAC"]},
        "Valine": {"code" : "V", "codon": ["GUU", "GUC", "GUA", "GUG"]},
        "Stop codons": {"code" : "STOP", "codon": ["UAA", "UAG", "UGA"]}
    }

  aa_sequence = []
  for codon in codons:
    found_match = False # Flag to check if a match was found
    for aa_name, info in aa_in_protein.items(): # Iterate through amino acid info
      # Ensure info["codon"] is always a list for consistent checking
      codons_list = info["codon"] if isinstance(info["codon"], list) else [info["codon"]]
      if codon in codons_list:
        aa_sequence.append(info["code"])
        found_match = True
        break # Found a match, move to the next RNA codon
    if not found_match:
      aa_sequence.append("X") # Placeholder for unrecognised codon
  return "".join(aa_sequence)


def central_dogma(dna_sequence):
  return translate_rna_to_protein(transcribe_dna_to_rna(dna_sequence))

bcr = "ATGGCCATTGTA"
print(characters_in_sequence(bcr))
print(classify_sequence(bcr))
print(transcribe_dna_to_rna(bcr))
rna = transcribe_dna_to_rna(bcr)
print(find_codons(rna))
print(translate_rna_to_protein(rna))
print(central_dogma(bcr))