# -*- coding: utf-8 -*-
""" HOPE Method 1.2.0 Puzzle 7 Phase 1

Author: Michellie Hernandez AI-assisted development: ChatGPT and Gemini were used for curriculum drafting, coding assistance and editorial feedback.
Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TKAMHCWPpgqSq9hTdR6bqgN-Ynie63OV

🧬 HOPE 1.2.0 — Puzzle 1

Today we're starting with the three sequence languages you'll use throughout the project.
The biological problem
HOPE 2.0 will eventually connect:
BCR nucleotide sequence → antibody protein sequence → proteomic peptides → reconstructed sequence
Before we reconstruct anything, your program needs to know what type of sequence it is looking at.
Remember:
DNA: A T G C
RNA: A U G C
Protein: amino-acid one-letter codes such as A C D E F G ...


Python skill
You'll practice:
variables
strings
len()
set()
for loops
if statements
🧩 Your challenge
Open your Google Colab notebook and create these three sequences:
dna = "ATGGCCATTGTA"
rna = "AUGGCCAUUGUA"
protein = "MAIV"
Then write Python code that answers:
1. How many characters are in dna?
2. How many characters are in rna?
3. How many characters are in protein?
4. What unique letters occur in each sequence?
5. Write an if statement that determines whether a sequence could be RNA based on whether it contains only A, U, G, and C.
For example, your program should eventually be able to distinguish:
AUGGCCAUUGUA  → RNA
ATGGCCATTGTA  → not RNA
MAIV          → not RNA
"""

dna = "ATGGCCATTGTA"
rna = "AUGGCCAUUGUA"
protein = "MAIV"

def characters_in_sequence(sequence):
  return len(sequence)

print(characters_in_sequence(dna))
print(characters_in_sequence(rna))
print(characters_in_sequence(protein))

def classify_sequence(sequence):
  aa_in_protein = {
    "Alanine": "A",
    "Arginine": "R",
    "Asparagine": "N",
    "Aspartic acid": "D",
    "Cysteine": "C",
    "Glutamic acid": "E",
    "Glutamine": "Q",
    "Glycine": "G",
    "Histidine": "H",
    "Isoleucine": "I",
    "Leucine": "L",
    "Lysine": "K",
    "Methionine": "M",
    "Phenylalanine": "F",
    "Proline": "P",
    "Serine": "S",
    "Threonine": "T",
    "Tryptophan": "W",
    "Tyrosine": "Y",
    "Valine": "V"
}
  if set(sequence).issubset({"A", "T", "G", "C"}):
        return "Sequence is DNA"

  elif set(sequence).issubset({"A", "U", "G", "C"}):
        return "Sequence is RNA"
  elif set(sequence).issubset(set(aa_in_protein.values())):
        return "Sequence is a Protein"
  else:
        return "Sequence is Unknown"



print(classify_sequence(dna))
print(classify_sequence(rna))
print(classify_sequence(protein))

